version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      meta_db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env

  meta_db:
    image: postgres:15
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meta_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "meta_db"]
      interval: 10s
      timeout: 60s
      retries: 5
    volumes:
      - meta_data:/var/lib/postgresql/data

volumes:
  meta_data:
